-- RUN THIS IN YOUR SUPABASE SQL EDITOR

-- Create confessions table
CREATE TABLE IF NOT EXISTS confessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sin TEXT NOT NULL,
  penance TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create members table
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  nap_duration TEXT,
  pizza_topping TEXT,
  vibe_check BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS
ALTER TABLE confessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;

-- Allow public insert/select for now (Not a Cult policy)
CREATE POLICY "Allow public insert on confessions" ON confessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on confessions" ON confessions FOR SELECT USING (true);
CREATE POLICY "Allow public insert on members" ON members FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select on members" ON members FOR SELECT USING (true);
